server:
  port: 10801
  servlet:
    context-path: /pulse
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://140.143.222.164:3306/pulse?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/pulse?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  mail:
    host: smtp.qq.com
    port: 465
    username: your_qq_email@qq.com    # 发件人邮箱
    password: your_smtp_auth_code     # SMTP 授权码
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

pulse:
  ai:
    # 全局配置
    socket-timeout: 60000          # 读取超时时间（毫秒）
    connect-timeout: 30000         # 连接超时时间（毫秒）
    write-timeout: 30000          # 写入超时时间（毫秒）
    retry-count: 3                # 重试次数
    enable-logging: true          # 是否启用日志
    enable-cache: false           # 是否启用缓存
    max-connections: 10           # 连接池最大连接数
    keep-alive-duration: 5        # 连接池保持连接时间（分钟）
  auth:
    secret: Sfsafaf#trggs
    expireTime: 30
  cache:
    mode: REDIS
    redis:
      host: 117.78.0.126
      port: 6379
      database: 0
      password: pulseuk


mybatis:
  # 指定mapper xml文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 指定实体类包路径
  type-aliases-package: com.*.*.**.domain
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




# 日志配置
logging:
  level:
    com.tran.pulse.service.DataCleanupService: INFO
    com.tran.pulse.service.CleanupTaskMonitorService: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"